# Your name and what you do
name: Jason Bhan
bio: Software Developer

description: Jason's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://jhbhan.github.io/website/

# do you want to display social media links? true or false
social-media: true

linkedin: https://www.linkedin.com/in/jhbhan/
github: https://github.com/jhbhan/
email: jhbhan.dev@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - React
    - Guitar
    - Korean Cuisine

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    MindDump:
        name: Mind-Dump
        description: little project i made for myself. contact me for any support at jhbhan.dev@gmail.com

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
